name: monitor-ambiental-web

services:
  web:
    container_name: monitor-ambiental-web
    build: .
    environment:
      - PORT=4000
      - API_UPSTREAM=http://monitor-ambiental-api:8000
    networks:
      - web

networks:
  web:
    external: true
